/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/common/Setting/About.vue')['default']
    Advanced: typeof import('./components/common/Setting/Advanced.vue')['default']
    Button: typeof import('./components/common/HoverButton/Button.vue')['default']
    General: typeof import('./components/common/Setting/General.vue')['default']
    GithubSite: typeof import('./components/custom/GithubSite.vue')['default']
    HoverButton: typeof import('./components/common/HoverButton/index.vue')['default']
    NaiveProvider: typeof import('./components/common/NaiveProvider/index.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NButton: typeof import('naive-ui')['NButton']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    PromptStore: typeof import('./components/common/PromptStore/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./components/common/Setting/index.vue')['default']
    SvgIcon: typeof import('./components/common/SvgIcon/index.vue')['default']
    UserAvatar: typeof import('./components/common/UserAvatar/index.vue')['default']
  }
}
